trigger:
- master

pool:
  vmImage: ubuntu-latest
#Pipelines -> stages ->jobs -> steps(tasks)

stages:
- stage: build
  jobs:
  - job: builddeployjob1
    steps:
    - script: echo Builddeployjob1
      displayName: 'Run a one-line script'
  
  - job: builddeployjob2
    steps:
    - script: echo Builddeployjob2
      displayName: 'Run a one-line script'
- stage: devdeploy
  dependsOn: build
  jobs:
  - job: devdeployjob2
    steps:
    - script: echo devdeployjob2
      displayName: 'Run a one-line script'
- stage: qadeploy
  dependsOn: devdeploy
  jobs:
  - job: qadeployjob3
    steps:
    - script: echo qadeployjob3
      displayName: 'Run a one-line script'
- stage: proddeploy
  dependsOn:
  - devdeploy
  - qadeploy
  jobs:
  - job: proddeployjob4
    steps:
    - script: echo proddeploy job4
      displayName: 'Run a one-line script'



