trigger:
- master

pool:
  vmImage: ubuntu-latest
#Pipelines -> stages ->jobs -> steps(tasks)

stages:
- stage: build
  jobs:
  - job: builddeployjob1
    steps:
    - script: echo Builddeployjob1
    - bash: echo $(PipelineLevelVariableValue)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranch)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: java -version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
  
#- stage: devdeploy
#  variables:
#    environment: dev
#  dependsOn: build
#  jobs:
#  - job: devdeployjob2
#   steps:
#    - script: echo $(environment)deployjob2
#      displayName: 'Run a one-line script'
#- stage: qadeploy
#  dependsOn: build
#  jobs:
#  - job: qadeployjob3
#    steps:
#    - script: echo qadeployjob3
#     displayName: 'Run a one-line script'
#- stage: proddeploy
#  dependsOn:
#  - devdeploy
#  - qadeploy
#  jobs:
#  - job: proddeployjob4
#    steps:
#   - script: echo proddeploy job4
#      displayName: 'Run a one-line script'



