trigger:
- master

#strategy:
#  matrix:
#    linux:
#      operatingSystem: 'ubuntu-latest'
#    mac:
#      operatingSystem: 'windows-latest'

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Buildjob
    steps:
    - bash: echo "Do the build"
- stage: Devdeploy
  jobs:
  - deployment: devdeployjob
    environment: dev
  - job: devjob
    steps:
    - bash: echo "Do the build"
- stage: qadeploy
  jobs:
  - deployment: devdeployjob
    environment: dev
  - job: qajob
    steps:
    - bash: echo "Do the qadeploy"
- stage: proddeploy
  jobs:
  - deployment: devdeployjob
    environment: dev
  - job: prodjob
    steps:
    - bash: echo "Do the proddeploy"

