# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: job1
  steps:
  - script: echo job1 Hello, world, changed
    displayName: 'Run a one-line script'

  - script: |
      echo echo hi there
      echo  This is kartheek
    displayName: 'Run a multi-line script'
- job: job2
  dependsOn: job1
  steps:
  - script: echo job2
    displayName: 'Run a one-line script'
- job: job3
  dependsOn: job2
  steps:
  - script: echo job3
    displayName: 'Run job3 a one-line script'

